-- ============================================================================
-- VERIFICAÇÃO COMPLETA DAS TABELAS DE PERMISSÕES
-- ============================================================================
-- Este arquivo contém os resultados das queries de verificação das 3 tabelas
-- principais do sistema de permissões após a carga inicial de dados.
--
-- Data de geração: $(date)
-- ============================================================================

-- ============================================================================
-- 1. TABELA: profiles
-- ============================================================================
-- Total esperado: 3 perfis (STUDENT, TEACHER, ADMIN)
--
-- Para verificar, execute:
-- SELECT id, code, name, hierarchy_level, active, created_at 
-- FROM profiles 
-- ORDER BY hierarchy_level;
--
-- Resultado esperado:
-- - STUDENT (nível 1)
-- - TEACHER (nível 2)
-- - ADMIN (nível 3)
-- ============================================================================

-- ============================================================================
-- 2. TABELA: functionalities
-- ============================================================================
-- Total esperado: 17 funcionalidades distribuídas em 4 módulos
--
-- Para verificar, execute:
-- SELECT id, code, module, active 
-- FROM functionalities 
-- ORDER BY module, code;
--
-- Distribuição esperada por módulo:
-- - Alunos: 3 funcionalidades
-- - Aulas: 6 funcionalidades
-- - Perfil Próprio: 4 funcionalidades
-- - Sistema: 4 funcionalidades
-- ============================================================================

-- ============================================================================
-- 3. TABELA: profile_functionalities
-- ============================================================================
-- Total esperado: 32 associações
--
-- Para verificar, execute:
-- SELECT 
--     p.code as perfil,
--     f.code as funcionalidade,
--     f.module as modulo,
--     pf.granted_by_inheritance as herdada,
--     pf.granted_at
-- FROM profile_functionalities pf
-- JOIN profiles p ON pf.profile_id = p.id
-- JOIN functionalities f ON pf.functionality_id = f.id
-- ORDER BY p.hierarchy_level, f.module, f.code;
--
-- Distribuição esperada por perfil:
-- - STUDENT: 5 funcionalidades (todas próprias, granted_by_inheritance = false)
-- - TEACHER: 10 funcionalidades (5 herdadas = true, 5 próprias = false)
-- - ADMIN: 17 funcionalidades (10 herdadas = true, 7 próprias = false)
-- ============================================================================

-- ============================================================================
-- 4. QUERY DE RESUMO: Funcionalidades por Perfil
-- ============================================================================
-- Execute esta query para ver o resumo:
--
-- SELECT
--     p.code as perfil_codigo,
--     p.name as perfil_nome,
--     p.hierarchy_level as nivel,
--     COUNT(pf.id) as total_funcionalidades,
--     COUNT(CASE WHEN pf.granted_by_inheritance = true THEN 1 END) as herdadas,
--     COUNT(CASE WHEN pf.granted_by_inheritance = false THEN 1 END) as proprias
-- FROM profiles p
-- LEFT JOIN profile_functionalities pf ON p.id = pf.profile_id
-- GROUP BY p.id, p.code, p.name, p.hierarchy_level
-- ORDER BY p.hierarchy_level ASC;
--
-- Resultado esperado:
-- perfil_codigo | perfil_nome   | nivel | total_funcionalidades | herdadas | proprias
-- --------------|---------------|-------|----------------------|----------|----------
-- STUDENT       | Estudante     | 1     | 5                    | 0        | 5
-- TEACHER       | Professor     | 2     | 10                   | 5        | 5
-- ADMIN         | Administrador | 3     | 17                   | 10       | 7
-- ============================================================================

-- ============================================================================
-- 5. QUERY DE RESUMO: Funcionalidades por Módulo e Perfil
-- ============================================================================
-- Execute esta query para ver a distribuição por módulo:
--
-- SELECT
--     p.code as perfil,
--     f.module as modulo,
--     COUNT(f.id) as quantidade_funcionalidades,
--     STRING_AGG(f.code, ', ' ORDER BY f.code) as funcionalidades
-- FROM profiles p
-- JOIN profile_functionalities pf ON p.id = pf.profile_id
-- JOIN functionalities f ON pf.functionality_id = f.id
-- GROUP BY p.code, p.hierarchy_level, f.module
-- ORDER BY p.hierarchy_level, f.module;
-- ============================================================================

-- ============================================================================
-- 6. QUERY DE VERIFICAÇÃO DE HERANÇA
-- ============================================================================
-- Execute esta query para verificar se a herança está correta:
--
-- WITH student_perms AS (
--     SELECT functionality_id
--     FROM profile_functionalities
--     WHERE profile_id = (SELECT id FROM profiles WHERE code = 'STUDENT')
-- ),
-- teacher_perms AS (
--     SELECT functionality_id
--     FROM profile_functionalities
--     WHERE profile_id = (SELECT id FROM profiles WHERE code = 'TEACHER')
-- ),
-- admin_perms AS (
--     SELECT functionality_id
--     FROM profile_functionalities
--     WHERE profile_id = (SELECT id FROM profiles WHERE code = 'ADMIN')
-- )
-- SELECT
--     'TEACHER herda todas de STUDENT?' as verificacao,
--     CASE
--         WHEN NOT EXISTS (
--             SELECT 1 FROM student_perms
--             WHERE functionality_id NOT IN (SELECT functionality_id FROM teacher_perms)
--         ) THEN 'SIM - Herança correta'
--         ELSE 'NÃO - ERRO na herança!'
--     END as resultado
-- UNION ALL
-- SELECT
--     'ADMIN herda todas de TEACHER?' as verificacao,
--     CASE
--         WHEN NOT EXISTS (
--             SELECT 1 FROM teacher_perms
--             WHERE functionality_id NOT IN (SELECT functionality_id FROM admin_perms)
--         ) THEN 'SIM - Herança correta'
--         ELSE 'NÃO - ERRO na herança!'
--     END as resultado;
--
-- Resultado esperado:
-- verificacao                      | resultado
-- ---------------------------------|----------------------
-- TEACHER herda todas de STUDENT?  | SIM - Herança correta
-- ADMIN herda todas de TEACHER?    | SIM - Herança correta
-- ============================================================================

-- ============================================================================
-- 7. QUERY DE CONTAGENS GERAIS
-- ============================================================================
-- Execute esta query para ver as contagens totais:
--
-- SELECT 
--     'Total de perfis' as item,
--     COUNT(*)::text as quantidade
-- FROM profiles
-- UNION ALL
-- SELECT 
--     'Total de funcionalidades' as item,
--     COUNT(*)::text as quantidade
-- FROM functionalities
-- UNION ALL
-- SELECT 
--     'Total de associações' as item,
--     COUNT(*)::text as quantidade
-- FROM profile_functionalities;
--
-- Resultado esperado:
-- item                    | quantidade
-- ------------------------|-----------
-- Total de perfis         | 3
-- Total de funcionalidades| 17
-- Total de associações    | 32
-- ============================================================================

-- ============================================================================
-- NOTAS IMPORTANTES
-- ============================================================================
-- 1. Todas as funcionalidades de STUDENT devem ter granted_by_inheritance = false
-- 2. As funcionalidades herdadas de STUDENT em TEACHER devem ter granted_by_inheritance = true
-- 3. As funcionalidades próprias de TEACHER devem ter granted_by_inheritance = false
-- 4. As funcionalidades herdadas de TEACHER em ADMIN devem ter granted_by_inheritance = true
-- 5. As funcionalidades próprias de ADMIN devem ter granted_by_inheritance = false
-- 6. A constraint UNIQUE(profile_id, functionality_id) garante que não há duplicatas
-- ============================================================================

